name: Node.js CI

on:
  pull_request:
    branches: [ "master", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    defaults: 
      run:
        working-directory: ./Frontend

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './Frontend/package-lock.json'
      - run: npm i
      - run: npm run build --if-present
      - name: Run tests
        run: npm test
