name: Full Stack CI

on:
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      # Solution principale
      - name: Restore dependencies for main solution
        run: dotnet restore .Backend/Backend.sln

      - name: Build main solution
        run: dotnet build .Backend/Backend.sln --no-restore -c Release
      
      # Solution de tests
      - name: Restore dependencies for test solution
        run: dotnet restore .BackendTest/BackendTest.sln

      - name: Run tests
        run: dotnet test .BackendTest/BackendTest.sln --no-restore --verbosity normal -c Release

  build-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Frontend

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './Frontend/package-lock.json'

      - name: Installation
        run: npm i
      - name: Build
        run: npm run build --if-present
      - name: Lancement des test
        run: npm test
